johnsonandjohnson/Bodiless-JS

- examples/test-site/src/components/Editors/asEditor.tsx
- hide overflowing part of editor placeholder
Another (and better) way to fix it would be to change the whitespace property of the placeholder itself, but it's not compatible with the current implementation where "whitespace: nowrap" is combined with "width: 0" to make the placeholder visible but not taking any space at the same time.
See this comment for more details:
https://github.com/ianstormtaylor/slate/issues/1344#issuecomment-340528377
- open any editable area, e.g. at /accordion example page
- make sure the placeholder doesn't overflow its container
Fixes #21
> fix(editor) Placeholder text overflows parent container

- packages/bodiless-organisms/src/components/SingleAccordion.tsx
- packages/bodiless-richtext/src/core/HoverMenu.tsx
- don't render hover menu if edit mode is not set
Fixes #23
> fix(richtext) Format bar persists when leaving edit mode

- packages/bodiless-core/src/contextMenuForm.tsx
- packages/bodiless-layouts/src/FlexboxGrid/helpers.tsx
Currently, we reusing `contextMenuForm` for every fly-out panel. Since we need to remove the submit button ( checkmark ) only for component picker window, I added `hasSubmit` to the `contextMenuForm` component options. `hasSubmit` defaults to `true` if not set.
Go to the `/flexbox` page and open component picker. There should not be a submit checkmark at the bottom of that window.
**GitHub Issue:** https://github.com/johnsonandjohnson/Bodiless-JS/issues/32
> Remove the Checkmark Icon from the Component Picker Window

- examples/test-site/src/templates/product_detail.jsx
- Add a set of Single Accordions to PDP template with non-editable accordion title.
- Create a product off /products.
- Verify you can add content to each accordion body and saves appropriately
- Verify you cannot edit title of accordion.
- Verify Accordion visually works
- None
> Add Accordion to PDP

- packages/gatsby-theme-bodiless/src/dist/GitProvider.tsx
We are descoping the Pull Changes Button Functionality from the Content Edit UI in the Main Menu.
**GitHub Issue:** https://github.com/johnsonandjohnson/Bodiless-JS/issues/30
> Remove the Pull Changes Button from the Edit UI

- examples/test-site/src/data/pages/flexbox/index.tsx
- packages/bodiless-layouts/src/FlexboxGrid/StaticFlexbox.tsx
Remove `bl-` prefixed classes from the `StaticFlexbox`.
1. Start the edit env by running `npm run start`
2. Go to `/flexbox` page and add some tacos.
3. Build and serve a static site by running `npm run build` and `npm run serve`
4. Go to `http://localhost:9000/flexbox/` and make sure there are no HTML elements with `bl-` classes left.
Fixes https://github.com/johnsonandjohnson/Bodiless-JS/issues/35
> Fix static Flexbox uses editor styles

- packages/bodiless-backend/package.json
Added `/src` to files in `/packages/bodiless-backend/package.json` so that it gets packed correctly.
1. Run `npm run sites:clone-local starter`
2. Run `npm run sites:update starter`
3. Go to `cd sites/starter`
4. Run `npm run build`
5. Run `npm run start`
ER: The app starts with no errors.
Fixes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/80
> fix:(bodiless-backend) Fix /src is missing in package.json

- examples/starter/.env.site
- examples/starter/README.md
- examples/test-site/.env.site
- examples/test-site/README.md
- package.json
- Add documentation on how to generate env variables to the example sites.
- Restructure `.env.site` comments style to follow the same pattern.
- Added `build:env-vars` script to the root package.json which leverages lerna to run `build:env-vars` script in all packages.
Relates to: https://github.com/johnsonandjohnson/Bodiless-JS/issues/50
> docs(examples): Add "How To" generate env vars and restructure .env.site comments.

- packages/bodiless-components/src/Image.tsx
- Removes the image-edit button from the global (left) context menu.
- Click on any image
- Verify that image edit button does not appear on left menu.
> fix(components): Remove image button from left menu.

- packages/bodiless-migration-tool/src/page-creator.ts
- packages/bodiless-migration-tool/src/scraper.ts
given source site has an internal url that is redirected to an external url
when the crawler follows this internal url
then the crawler returns sources of external url to migration tool
then the migration tool should not create a page for this kind of url
> fix(bodiless-migration-tool): do not create a page when an internal url is redirected to an external

- packages/bodiless-richtext/src/MobxStateContainer.ts
- packages/bodiless-richtext/src/useNodeStateHandlers.ts
* improved richtext input lag on a page with multiple richtext elements
* bodiless richtext observes mobx richtext store (MobxStateContainer). before this fix, richtext component reacts to any changes to the store which leads to unnecessary renders of all richtext on the page when changes are made to any richtext component. after this fix, richtext observers and react to only each own key from the mobx store. 
Place many slate editors on the same page (eg on slate-api page, add >20 copies of the same editor, pointing to different nodes.
ER: Editors are as responsive to kestrokes as if there is only one.
AR: Editors exhibit significant keyboard lag.
> fix(bodiless-richtext): improved richtext input lag on a page with multiple richtext elements

- .travis.yml
Alex removed the npm run build from .travis.yml
so the docs aren't getting built
we didn't catch it on the branch bc the deploy of hte docs only happens on master
> chore(cypress): fixing build - added npm run build:doc

- examples/starter/package.json
- packages/bodiless-migration-tool/package.json
Use 'cross-env' package to pass variables in inline npm scripts on Windows.
Fixes #111
> fix(migration_tool): 'npm run setup' fails on Windows

- packages/bodiless-backend/README.md
- packages/bodiless-backend/src/backend.js
* adjusted bodiless-backend so that it does not fail when development packages morgan and morgan-body are not installed
1. npm i @bodiless/backend@0.0.40
2. node ./node_modules/@bodiless/backend/src/server.js
**AR:** Error: Cannot find module 'morgan'
**ER:** The server started without errors
> fix(bodiless-backend): do not require morgan when it is disabled

- cypress/integration/link_menu.spec.js
- cypress/integration/smokeTest/touts_spec.js
- packages/bodiless-components/__tests__/Image.test.tsx
- packages/bodiless-components/__tests__/Link.test.tsx
- packages/bodiless-core/__tests__/StaticPage.test.tsx
- packages/bodiless-core/src/PageEditContext/index.tsx
- packages/bodiless-richtext/__tests__/RichText.test.tsx
* edit ui starts in preview mode
* the flag containing edit ui mode is stored in browser sessions storage
* see #160
* closes #160
> feat(bodiless-core): edit ui should start in preview mode

- examples/test-site/src/data/pages/index.tsx
- packages/bodiless-components/src/Placeholder.tsx
- packages/bodiless-components/src/index.ts
- This PR adds new `withEditPlaceholder` HOC to `@bodiless/components`.
- When used this HOC rendered `PlaceholderComponent` when in `edit` mode and an original component when on `static` site or in `preview` mode.
You can create test components on any page of the `test-site`. 
- Open `Bodiless-JS/examples/test-site/src/data/pages/index.tsx` and add `withEditPlaceholder` to `@bodiless/components` imports:
```js
import {
..., withEditPlaceholder,
} from '@bodiless/components';
```
- In the same file ( `index.tsx` ) create 2 test components: any component and it's placeholder. For example:
```js
const TestComponent = props => (
<div {...props}>Test Component</div>
);
const PlaceholderComponent = props => (
<div {...props}>Placeholder Component</div>
);
```
- Use `withEditPlaceholder` to …
> feat(components): Add withEditPlaceholder HOC to bodiless-components

- packages/bodiless-migration-tool/src/helpers.ts
- packages/bodiless-migration-tool/src/scraper.ts
- packages/bodiless-migration-tool/src/site-flattener.ts
- packages/bodiless-migration-tool/tests/helpers.test.ts
- packages/bodiless-migration-tool/tests/site-flattener.test1.ts
* when operator specifies a url without www in migration-settings.json (for instance, https://example.com), then urls with www (https://www.example.com) and without www (https://example.com) will be scraped. vice versa, when an operator specifies a url with www in migration-settings.json (for instance, https://www.example.com), then urls with www (https://www.example.com) and without www (https://example.com) will be scraped
* when operator specifies a url without protocol in migration-settings, then the protocol is automatically prepended to the url
* see #165 
* Fixes #165
> fix(bodiless-migration-tool): allow to migrate a site with bareroot domain specified

- packages/bodiless-core-ui/src/GlobalContextMenu.tsx
- Add `id` attr to the `GlobalContextMenu`
- Add `aria-label` attr to the `GlobalContextMenu`
- If `GlobalContextMenu` positioned on the **left** side it will have `aria-label="Global Context Menu Left"`
- If `GlobalContextMenu` positioned on the **right** side it will have `aria-label="Global Context Menu Right"`
> chore(core-ui): Improve Editor Menu Selectors

- packages/bodiless-components/src/Placeholder.tsx
- packages/bodiless-core/src/withEditToggle.tsx
- Fix withEditPlaceholder components order so that the placeholder component is displayed on edit envs instead of static.
You can create test components on any page of the `test-site`. 
- Open `Bodiless-JS/examples/test-site/src/data/pages/index.tsx` and add `withEditPlaceholder` to `@bodiless/components` imports:
```js
import {
..., withEditPlaceholder,
} from '@bodiless/components';
```
- In the same file ( `index.tsx` ) create 2 test components: any component and it's placeholder. For example:
```js
const TestComponent = props => (
<div {...props}>Test Component</div>
);
const PlaceholderComponent = props => (
<div {...props}>Placeholder Component</div>
);
```
- Use `withEditPlaceholder` to wrap `TestComponent` and pass `PlaceholderComponent`:
```js
const TestComponentWithPlaceholder = …
```
> fix(components, core): Fix withEditPlaceholder components order

- packages/bodiless-psh/resources/static/static.platform.app.yaml
- Disable `passthru` for the static app on psh to display default 404 page
- On a static site open any non-existing page.
- You should see a default p.sh 404 page.
> fix(psh): Platform.sh site return 502 error instead of 404 page on non-existing pages.

- packages/bodiless-psh/resources/.platform/platform.whitelist.yaml
- packages/bodiless-psh/src/bodiless-psh-init.ts
- `expires` key was added for `/__docs` path.
- Deploy a site to p.sh using updated `@bodiless/psh` package.
- Open Docs
- Check the `network` tab in the chrome console.
- You should see the `Cache-Control` and `Expires` headers enabled.
Fixes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/172
> fix(psh): Provide default psh cache expiry for /__docs

- packages/bodiless-backend/src/backend.js
- Checkout the repo using https as git remote origin.
- Alter github credential so commits can not be pushed to origin successfully.
- Setup edit site
- Make some changes and commit.
Fixes #274
> fix(Backend): commit operation throws 'authentication failed' error with an exposed password.

- packages/bodiless-richtext/src/useNodeStateHandlers.ts
* fixed the issue that richtext content on a contentful tout is not reverted until the page is refreshed
* enabled back the logic responsible for combining richtext mobx store data with content node data to pass value prop to slate editor component.
* the reason the logic was commented out is to deal with performance issues in slate editor. but taking into consideration other performance optimizations were made for slate editor and commenting out the logic breaks data propagation from the server, the logic is enabled back.
Notes:
* the changes may impact richtext performance. a test should be made if the difference is noticeable to the user 
STR1 (vanilla richtext)
1. open edit app of test-site
2. open /richtext page
3. type some text to "Simple Rich Text"
4. find related json file on …
> fix(richtext): richtext content is not reverted until page is refreshed

- .vscode/settings.json
- cypress/integration/link_menu.spec.js
- cypress/integration/smokeTest/editorMenu_spec.js
- cypress/integration/smokeTest/linkToggle_spec.js
- cypress/integration/smokeTest/singleAccordion_spec.js
- cypress/integration/smokeTest/touts_spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- examples/test-site/src/components/FlowContainer/token.tsx
- packages/bodiless-backend/__tests__/getChanges.test.ts
- packages/bodiless-components/__tests__/Image.test.tsx
- packages/bodiless-components/__tests__/Link.test.tsx
- packages/bodiless-core-ui/src/ReactTags.tsx
- packages/bodiless-core/__tests__/hoc.test.tsx
- packages/bodiless-core/__tests__/withSidecarNodes.test.tsx
- packages/bodiless-core/src/index.ts
- packages/bodiless-core/src/withSidecarNodes.tsx
- packages/bodiless-documentation/doc/Development/Architecture/Data.md
- packages/bodiless-layouts/__tests__/ComponentSelector/componentSelectorForm.test.tsx
- packages/bodiless-layouts/__tests__/FlexboxGrid/model.test.ts
- packages/bodiless-layouts/__tests__/FlexboxGrid/useGetMenuOptions.test.tsx
- packages/bodiless-layouts/src/ComponentSelector/componentSelectorForm.tsx
- packages/bodiless-layouts/src/FlowContainer/__mocks__/model.ts
- packages/bodiless-migration-tool/conf/template_dangerous_html.jsx
- packages/bodiless-migration-tool/src/page404-handler.ts
- packages/bodiless-migration-tool/tests/data/template_dangerous_html.jsx
- packages/bodiless-migration-tool/tests/page404-handler.test.ts
- packages/bodiless-psh/resources/static/static.platform.sh
- packages/bodiless-richtext/__tests__/HoverMenu.test.tsx
Adds an API for creating "sidecar" node hierarchies,
effectively allowing an enhancing HOC to hang its
data off of the component it wraps without changing
the node that is passed to that component.
See docs and functional tests.
#285
Closes #321
> feat(core): Sidecar Node API

- examples/test-site/src/data/pages/context/index.tsx
- packages/bodiless-core/__tests__/ContextProvider.test.tsx
- packages/bodiless-core/src/Contentful/withResetButton.ts
- packages/bodiless-core/src/hoc.tsx
- packages/bodiless-core/src/index.ts
- packages/bodiless-core/src/withEditButton.tsx
- packages/bodiless-layouts/src/SlateSortableResizable.tsx
- packages/gatsby-theme-bodiless/src/dist/GitProvider.tsx
- Remove all internal references to `withPageContext`. This was always exported as `withMenuOptions`, now the internal naming is consistent.
- Remove export of `PageContextProvider` as `ContextProvider` (now exported as `PageContextProvider`)
> chore(core): Fix legacy naming

- packages/gatsby-theme-bodiless/__tests__/GatsbyMobxStoreItem.test.ts
- packages/gatsby-theme-bodiless/src/dist/GatsbyMobxStoreItem.ts
- packages/gatsby-theme-bodiless/src/dist/types.ts
* when an error occurs after saving data to the backend, the request is retried until successful
* retry delay is incrementally increased between subsequent failed requests
Fixes #394
> feat(gatsby-theme-bodiless): Retry on Error When Saving to the Backend

- packages/bodiless-backend/src/backend.js
Make git revert operation considering location of .git folder and resolve path base on that.
This is important when launching the site outside the monorepo.
- launch starter site by running `npm run sites:launch-test` or in a standalone folder
- init clean git repo in the site folder, add and commit everything
- try adding and reverting new pages in edit mode
Fixes #427
> Fix (core, backend): Revert operation - consider location of root git folder

- examples/test-site/src/data/pages/form-elements/index.tsx
- packages/bodiless-core-ui/src/GlobalContextMenu.tsx
- packages/bodiless-core-ui/src/LocalContextMenu.tsx
- packages/bodiless-core/src/Types/ContextMenuTypes.tsx
- packages/bodiless-layouts/src/ComponentSelector/FilterWrapper.tsx
- packages/bodiless-layouts/src/ComponentSelector/types.tsx
- packages/bodiless-ui/src/elements.tsx
- Add remaining elements from https://joepuzzo.github.io/informed/?path=/story/inputs--intro
- Add example 'form-elements' page
- Go to /form-elements page
- Make sure it follows the wireframe https://jhdfdc.axshare.com/#id=3ct389&p=aries
Closes #336
> Feat (core, ui): Add remaining informed components

- packages/bodiless-cli/README.md
Remove README placeholder for replacement.
- Run cmd
```git clone https://github.com/dewen/Bodiless-JS.git -b feat/package-release-failed-due-to-auto-readme-md-update-during-prepack BodilessJS504 && \
cd BodilessJS504 && \
npm run setup && \
cd packages/bodiless-cli && \
sed -i '' 's/0.0.52/0.0.53/g' package.json && \
./node_modules/.bin/oclif-dev readme && \
git diff README.md
```
Expect:
- No README.md changes (it will replace version to 0.0.53 before fix).
> Package Release failed due to @bodiless/cli auto README.md update

- examples/starter/src/components/FlowContainer/withRichTextVariations.tsx
- examples/test-site/src/components/FlowContainer/withRichTextVariations.tsx
* removed richtext filter from flow container
1. open a page with flow container on starter or test-site
2. click add item
3. tick "RichText" in Type filter
Expected: no Richtext filter displayed
Fixes: #461
> feat(test-site, starter): removed richtext filter from flow container

- packages/bodiless-core/src/hooks.ts
- Click outside is now registered on `mousedown` instead of `click`
> fix(core): Context Menu Panel for link/image/seo disappear when you mouse moves off

- packages/gatsby-theme-bodiless/src/dist/GatsbyImage/asGatsbyImage.tsx
- packages/gatsby-theme-bodiless/src/index.ts
* fixed the issue when image attrs including alt and title are not rendered when gatsby image is activated
> fix(gatsby-theme-bodiless): allow to pass props to gatsby img

- packages/bodiless-richtext/src/serializers/htmlSerializer.ts
- Ensure richtext deserializer does not product elements with empty children.
Fixes #791.
> fix(richtext): #791 - Fix crash when pasting empty last element.

- packages/bodiless-components/src/Breadcrumbs/withBreadcrumbs.tsx
- packages/bodiless-organisms/__tests__/SimpleMenuBreadcrumbs.test.tsx
- packages/bodiless-organisms/__tests__/__snapshots__/SimpleMenuBreadcrumbs.test.tsx.snap
* fix(components): Breadcrumbs lost when a component context is activated in edit mode
* root cause of the issue is that when a component composed with `withBreadcrumbStore` hoc is rerendered then breadcrumb store is reinitialized and breadcrumb store items are lost
> fix(components): Breadcrumbs lost when a component context is activated in edit mode

- packages/bodiless-richtext/bodiless.docs.json
- Add correct asset file names to Rich Text Component bodiless.docs.json file 
Issue: 
#810
> fix(docs): Images still missing from docs

- examples/starter/src/components/Menu/SimpleMenu.token.tsx
- examples/starter/tailwind.config.js
- examples/test-site/src/components/Menu/SimpleMenu.token.tsx
- examples/test-site/tailwind.config.js
- packages/bodiless-organisms/src/components/Menu/SimpleMenu.token.tsx
- packages/bodiless-organisms/tailwind.config.js
- 'w-content' is moved from the Bodiless to test-site and starter
- Make sure menus on the test-site look and function the same as in prod.
Closes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/817
> fix(organisms): Remove w-content token from Menu and move it to test site

- examples/test-site/src/data/pages/richtext/index.tsx
- packages/bodiless-core/__tests__/withChild.test.tsx
- packages/bodiless-core/src/withChild.tsx
* replaced existing withChild hoc so that it is possible to alter the added child using the design API.
* for testing purposes, a new richtext called "Alphabetic Full Rich Text"  is added to /richtext page of test-site. Leveraging the implemented API, the richtext accepts only alphabetic characters, space, backspace, delete and enter characters. Please note that the richtext configured so that the logic to disallow characters works only during typing (it still will be possible to insert non-alphabetic characters using pasting)
Fixes: #797
> feat(core): designable child API

- packages/bodiless-core-ui/src/LocalContextMenu.tsx
- packages/bodiless-core/src/PageEditContext/types.ts
- packages/bodiless-core/src/Types/ContextMenuTypes.tsx
- packages/bodiless-core/src/components/ContextMenu.tsx
* added event listener on local menu group title to activate item on click
* underlined title of leftmost group
* added style for underline not active elements on hover
* open Homepage 
* select Edit mode
* click on Image inside block "Giving back to community"
* make sure the conditions are met:
AC1. When you click the group title on the local context menu, the corresponding context is activated
AC2. There is a hover effect on the group title which indicates an interaction (underline).
AC3. The left most (inner most) group title is always underlined.
Group title will be **not clickable** and **without any additional styles** in case a group contains only one element.
> feat(bodiless-core-ui): activate context for group in Local context menu

- packages/bodiless-layouts/src/FlowContainer/useGetMenuOptions.tsx
* fixed an issue regarding incorrect context menu order of inner empty flow container
* the problem caused by having multiple context menu items with the same name 'add'. The first item is added by outer flow container. The second item is added by inner flow container. Because of the same name, the inner item overwrites the outer one and takes the outer item position which takes precedence over flow container item menu  items (add, swap, delete).The fix made is to ensure 'add' menu item of outer and inner flow containers have different name
Steps to reproduce
* add an inner flow container
* activate inner flow container local context menu
AR: Inner flow container context menu is displayed after outer flow container context menu
ER: Inner flow container context menu is displayed before …
> fix(layouts): nested flow container context menu order

- packages/bodiless-layouts/src/ContentLibrary/withContentLibrary.tsx
- Content library button now correctly merges with buttons provided by the component to which it is attached.
Fixes #911
> fix(core): Content library button did not merge properly.

- packages/fclasses/__tests__/FClasses.test.tsx
- packages/fclasses/src/FClasses.tsx
- This is a short term fix for numerous type errors when trying to use addClasses with asToken.  Will be fixed permanently in scope of #919 , but should serve to reduce casts in the short term.
> fix(fclasses): Short term fix for addClasses type error.

- examples/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.token.tsx
- packages/bodiless-components/src/Editable.tsx
- packages/bodiless-navigation/src/Breadcrumbs/Breadcrumb.token.tsx
- packages/bodiless-navigation/src/Breadcrumbs/hooks.ts
* when last breadcrumb item is not a link, then 'aria-current' attribute is added to the corresponding 'li' html element
> fix(navigation): breadcrumb current-page attribute

- packages/bodiless-components/src/Link/asBodilessLink.tsx
- Ensure that a bodiless link can receive a target prop.
> fix(components): Allow link target to be passed as prop.

- examples/test-site/src/components/Menu/Menu.token.tsx
- examples/test-site/src/data/pages/menu/index.tsx
- packages/bodiless-navigation/src/Menu/Menu.token.tsx
- Fix `asTopNav` preventing it from adding every submenu option from being added to the Chameleon component picker regardless of the submenu type being used.
- Make sure the Site Navigation menu works the same as in the production.
- Check two new menu examples on the /menu/ page.
- One should add a List submenu automatically without the Chameleon picker
- Another menu example should only have List and Columns options.
> fix(navigation): Fix asTopNav adding every submenu option to Chameleon.

- packages/bodiless-search/src/components/Suggestions.tsx
> fix(search): Typeahead/suggestion item click does not trigger the search

- cypress/integration/smokeTest/singleAccordion_spec.js
- packages/bodiless-accordion/src/components/AccordionWrapper.tsx
- `aria-labelledby` attributes are now generated for accordions that don't have `AccordionClean` as a start component and rely on `asAccordionWrapper` to provide the context.
> fix(accordion): 'aria-labelledby' refers to a missing element, or is empty

- examples/test-site/src/components/Menu/BurgerMenu.token.tsx
- packages/bodiless-core/src/withChild.tsx
- packages/bodiless-navigation/src/Menu/asAccessibleMenu.tsx
- Function names of `withAppendChild` & `withPrependChild` names are swapped to match actual functions behavior in bodiless-core.
This change has an impact on the below area and needs to be tested accordingly.
- /packages/bodiless-navigation/src/Menu/asAccessibleMenu.tsx ( Only the `SubmenuIndicator` may be affected )
- /examples/test-site/src/components/Menu/BurgerMenu.token.tsx ( Only the BM Toggle Button may be affected )
Closes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/1067
> Update withAppendChild and withPrependChild

- packages/bodiless-table/src/asBodilessTable.tsx
Fixed `useNode` returning a Cell's parent node, instead of returning the Cell node, by changing a `withDesign` call on the `asBodilessTable` token to `withFinalDesign`.
As mentioned in #1032:
- Wrap a table element in an `asBodilessTable`
- Add an HOC via `withDesign` to a table cell which uses the current node, like:
```ts
import { CleanTable } from '@bodiless/table';
const withTestHOC: HOC = Component => {
const WithTestHOC = (props: any) => {
const { node } = useNode();
console.debug(node.path);
return <Component {...props} />;
};
return WithTestHOC;
};
const Table = asToken(
withDesign({
Cell: withTestHOC,
}),
)(CleanTable);
```
- Add some data to the table, or apply the `withTestHOC` token to an existing table on the `/table` page.
The `node` constant should represent the Cell node, …
> Fix table cell returning parent node on useNode

- .github/workflows/build-test-lint-simple.yml
- packages/bodiless-components/src/GTM/gtm.tsx
On legacy/0.1 branch Sites running with rocketloader are pushing duplicate events
/bodiless-components/src/GTM/gtm.tsx#L113
- Add GTM container ID in env.site
- Enable rocket loader on cloudlfare
- Open the developer console on browser
- There should be only 1 even fired from GTM data layer.
> fix(GTM): Sites running with rocketloader are pushing duplicate events - Legacy

- .github/workflows/build-test-lint-simple.yml
- packages/bodiless-components/src/GTM/gtm.tsx
Sites running with rocketloader are pushing duplicate events
/bodiless-components/src/GTM/gtm.tsx#L113
- Add GTM container ID in env.site
- Enable rocket loader on cloudlfare
- Open the developer console on browser
- There should be only 1 even fired from GTM data layer.
> fix(GTM): Sites running with rocketloader are pushing duplicate events

- examples/test-site/src/data/pages/gallery-final/index.tsx
- packages/bodiless-documentation/doc/Development/Architecture/Data.md
- packages/bodiless-documentation/doc/Development/Guides/IntroToBodilessConcepts.md
Update documentation to warn about potential module resolution issues if a node key produces a json file with the same name as a source module in the same directory.
> doc(core): Add notes about node key conflicts with module names

- .github/workflows/docs.yml
- .github/workflows/publish.yml
Upgrade GitHub action ubuntu version to the latest in order to unlock the automated release process.
https://github.com/johnsonandjohnson/Bodiless-JS/issues/1120
https://github.com/johnsonandjohnson/Bodiless-JS/pull/1119/files#diff-9cf2000c53760d837a449f874e53f792819108d3a4bf346336d0f7d082deae2cR14
> chore: pre-Release-v0.2.10

- packages/bodiless-documentation/doc/Development/Guides/BuildingSites/TailwindGuide.md
- Update documentation regarding site-level Tailwind configuration file (`site.tailwind.config.js`) being optional.
**Documents:**
- #1199 
---
Resolves #1279
> docs(bodiless-documentation): Site-Level Tailwind Config Optional (#1279)

- packages/bodiless-richtext/src/core/Content.tsx
Fix inline placeholders inside Rich Text Editors wrapping text, which made them unreadable and hard to click on.
> fix(richtext): Fix RTE inline placeholders wrapping text

- packages/gatsby-theme-bodiless/package.json
The `babel-plugin-preval` package was added as a dev-only dependency, but it is actually required in projects using Bodiless. This PR moves the package to the normal dependency list.
> fix(gatsby-theme-bodiless): Fix missing babel-plugin-preval dependency

- examples/starter/gatsby-node.js
- examples/starter/package.json
- examples/test-site/gatsby-node.js
- examples/test-site/package.json
- packages/gatsby-theme-bodiless/gatsby-node.js
This fixes the problem which made Webpack not trigger new builds when changing files outside the current site folder, eg. a package file.
Webpack 5 implemented a new optimization to ignore "immutable" folders when watching for changes. By default, everything inside `node_modules` is ignored, since files inside this folder don't normally change. This overrides the default by ignoring all folders inside `node_modules`, except the `@bodiless` folder.
Start a test-site or starter server, wait for the build to finish and change any TS file inside any Bodiless package. The server should trigger a new build automatically, as expected.
> fix(gatsby-theme-bodiless): Fix changes on bodiless packages not triggering rebuilds

- packages/bodiless-navigation/src/Breadcrumbs/asBreadcrumb.tsx
Breadcrumb is losing data on preview mode, after switching to edit mode and switching back to preview.
- Reorganize logical condition to apply useEffectCallback on breadcrumb data.
Recheck breadcrumbs.
N/A.
> bugfix(breadcrumb-store-render): Fix Data Missing From Breadcrumb On Preview

- sites/test-site/src/components/Breadcrumbs/MenuBreadcrumbs.ts
Breadcrumb base hoc name renamed but it was not updated in the only import that's using it on the test site (See https://github.com/johnsonandjohnson/Bodiless-JS/blob/chore/upgrade-deps/sites/test-site/src/components/Layout/index.tsx#L31).
Update "Breadcrumbs" to "BreadcrumbsBase"
N/A
N/A
> bugfix(menu-breadcrumbs): Fix Export Of Breadcrumb Base

- .github/workflows/build-test-lint-simple.yml
- package.json
Cypress tests are failing with standalone, due to missing packages (still to be further investigated). Right now, we are temp changing it to run on monorepo.
We provide site launch and test for monorepo and call it in github workflow actions.
N/A
N/A
> bugfix(cypress): Run Cypress On Monorepo

- cypress/integration/smokeTest/cards_spec.js
- cypress/integration/smokeTest/pdp_spec.js
- cypress/support/commands.js
- packages/bodiless-backend/__tests__/fixtures/git/get-changes/hooks/prepare-commit-msg.sample
- packages/bodiless-backend/__tests__/fixtures/git/get-conflicts/hooks/prepare-commit-msg.sample
- packages/bodiless-core-ui/src/LocalContextMenu.tsx
- sites/test-site/src/data/pages/chameleon/index.tsx
Cypress isImageVisible calls are commented out and some strings of "examples" have been replaced with "sites".
Reverted back isImageVisible calls and updated attachFile function since it has been changed a little after cypress upload.
Also, replaced some occurrences of "sites" to "examples".
N/A
N/A
> bugfix(cypress-image-is-visible): Revert isImageVisible and Comments

- packages/gatsby-theme-bodiless/gatsby-node.js
- sites/__cxstarter__/package.json
- Add bodiless backend as a dependencey of starter (solves cannot find server.js)
- remove unnecessary babel plugin (solves numerous console warnings during build)
> fix(starter, gatsby-theme): missing server and other gatsby start warnings on starter.

- .github/workflows/create-qa-branch.yml
- Action to create daily QA branch from repo's default branch and spin up psh envs added.
> feat: action to create daily qa branch implemented

- packages/fclasses/src/replaceable.tsx
Fix https://github.com/johnsonandjohnson/Bodiless-JS/issues/706 by only passing `key` and `children` props to Fragments, instead of all props available.
> fix(fclasses): Fix replaceWith passing extra props to Fragments

- .platform.app.yaml
- packages/fclasses/__tests__/TokenSpecTypes.test.ts
- packages/fclasses/__tests__/tokenSpec.test.tsx
- packages/fclasses/src/tokenSpec.ts
- packages/fclasses/src/types.ts
- asTokenSpec now supplies empty objects for domains which are not specified in the input
- Fixes issue where tokens were altered when using asTokenSpec to extend
Fixes #1496 
Closes #1525
> feat(fclasses): asTokenSpec produces token with all domains

- packages/bodiless-backend/package.json
- packages/bodiless-backend/src/fileHelper.js
- packages/bodiless-layouts/package.json
- packages/bodiless-layouts/src/FlowContainer/EditFlowContainer.tsx
- packages/bodiless-layouts/src/deserializers/createFlowContainerItem.ts
- packages/bodiless-tokens/package.json
- packages/bodiless-tokens/src/TokenEditor/withTokenEditorComponent.tsx
- packages/bodiless-tokens/src/withTokenSelector.tsx
- packages/gatsby-theme-bodiless/create-node.js
- packages/gatsby-theme-bodiless/gatsby-node.js
- packages/gatsby-theme-bodiless/package.json
- packages/gatsby-theme-bodiless/src/dist/DefaultContent/createPlugins.ts
crypto-browserify bring inside the bundle a dependencies to two versions of bn.js and readable-stream, resulting in bn.js included in the bundle 6 times, readable-stream 2 times.
Instead of using crypto and then fallback it using crypto-browserify, use directly crypto-js solve the issue.
E.g. test-site bundle is reduced by 737.25 KB to 577.27 KB
> feat(gatsby-theme-bodiless): Replace crypto-browserify with crypto-js

- UPGRADE.md
- packages/vital-elements/doc/Tokens.md
- sites/test-site/src/data/pages/api/fclasses/index.tsx
- sites/test-site/src/data/pages/chameleon/index.tsx
- sites/test-site/src/data/pages/gallery-final/Gallery.tsx
Issue: Tailwind site has defined its color and doesn't use tailwind default colors (so yellow, green & purple still exist) and shouldn't have gotten the search replacement.
* Color palette changes -- 
** replaced -green- with -emerald-
** replaced -yellow- with -amber-
** replaced -purple- with -violet-
Fix: 
- Revert emerald back to test sites color 'green' instead on test site only
- Revert amber back to test sites color 'yellow' instead on test site only
Fix will restore following issues:
- /chameleon will change to green or yellow
- /api/fclasses/ button on click will turn green
- /gallery-final/ placing a green component will have green border.
confirmed no cases of replacement in test site for
** replaced -purple- with -violet-
> fix(test-site): use test site colors

- packages/bodiless-accordion/src/components/Accordion.tokens.tsx
- packages/bodiless-accordion/src/components/SingleAccordion.tsx
- packages/bodiless-components-ui/src/FileUpload.tsx
- packages/bodiless-layouts-ui/src/ComponentSelector.tsx
- packages/bodiless-layouts-ui/src/DragHandle.tsx
- packages/bodiless-layouts/src/ContentLibrary/ContentLibraryIndicator.tsx
- packages/bodiless-navigation/src/BurgerMenu/BurgerMenu.token.tsx
- packages/bodiless-navigation/src/Menu/asAccessibleMenu.tsx
- packages/bodiless-navigation/src/icons/ExpandMore.tsx
- packages/bodiless-navigation/src/token.tsx
- packages/bodiless-organisms/src/components/SocialShare/index.tsx
- packages/bodiless-richtext/src/components/PluginButton.tsx
- packages/bodiless-richtext/src/components/TextSelectorButton.bl-edit.tsx
- packages/bodiless-search/src/components/ResponsiveSearchBox.tsx
- packages/bodiless-ui/README.md
- packages/bodiless-ui/bodiless.tailwind.config.js
- packages/bodiless-ui/index.tailwind.css
- packages/bodiless-ui/src/elements.tsx
- Replaced material-icons with bl-material-icons and brought over the material icon styling from tailwind so we are not dependent on that material icons css coming from google.
- Accordion -- removed material-icons as we switched to svg and these were just extra class material-icon not removed.
- BurgerMenu toggler -- same as above
- Searchresults box in desktop header -- same as above
- Menu: SubMenu indicator was dependent on google font material icons -- switched to SVG 
- Any icons in editor could be affected.
- On UX components confirm icons appear as expected for:   Accordion, Burgermenu toggler, Submenu indicator for Menu
> fix(material-icons): remove dependency on google fonts material fonts css & clean up of components.

- packages/bodiless-layouts-ui/src/ComponentSelector.tsx
- packages/bodiless-richtext-ui/src/components/PreviewWrapper.tsx
- packages/bodiless-ui/bodiless.tailwind.config.js
- packages/bodiless-ui/index.tailwind.css
- packages/bodiless-ui/src/elements.tsx
* Defined Icon size more clearly and applied to appropriate cases
* Removed icon color in material-icons styling
* Switch preview of RTE in component picker to same background in real-use
> fix(bodiless-ui): fix icon size & color

- sites/test-site/src/components/Layout/logo.tsx
…go after opening Email on /social-share/
fixes: #1601
> fix(test-site, GatsbyLink): There is a runtime error when clicking Logo after opening Email on /social-share/

- edit/platform.custom.sh
- edit/platform.sh
Prevent p.sh deploy script from building docs and vars for every site in sites folder.
Run it only for the site specified in APP_SITE_NAME.
> fix(psh): run build:doc and build:env-vars only for current site

- packages/bodiless-backend/src/page.js
- packages/bodiless-page/src/types.ts
There is an issue to clone the homepage in case there is an image uploaded to any components. This is happening because replacing function is not updating properly the page. We are refactoring the backend function to update the cloned assets to use simple template string instead of regex.
- Replace regex with template strings to build the paths to replace/be replaced;
- Additionaly, we update bodiless page client type to include clone
N/A
- #1608
> fix(bodiless-backend): Fix image assets paths to be replaced on clone operation

- packages/bodiless-layouts/src/FlowContainer/SortableContainer.tsx
* remove isActive for class as it leaves a permanent orange class on empty flow-containers.
> fix(bodiless-layouts): only orange on hover

- .github/workflows/prerelease.yaml
To fix an issue where NPM was installing canary versions of Bodiless packages when using `^1.0.0-beta.X` on our dependencies, we will now release `rc` versions when running the pre-release action.
This means that, instead of releasing `1.0.0-beta.X` on our next pre-release, we will now release `1.0.0-rc.X`.
Note that `1.0.0-rc.1` is already out on the main branch, so we're already using `rc` releases on all our packages, and there's no further actions needed.
> ci: Release RC versions on prerelease

- .github/workflows/pr-canary-release.yml
Fixed checkout for pull_request_target event of github workflow to use merge commit (main + pr changes, as regular pull_request event does) instead of main branch only.
Closes #1807
> fix: checkout to merge commit on pull_request_target event

- packages/bodiless-ga4/doc/GA4Activation.md
- sites/minimal-demo/.env.site
Remove ref to env variable as it doesn't exist.
No testing needed.
> docs(bodiless-ga4): Remove ref to env var

- packages/vital-layout/src/components/Footer/CopyrightRow/CopyrightRowClean.tsx
- packages/vital-layout/src/components/Footer/CopyrightRow/index.bl-edit.ts
- packages/vital-layout/src/components/Footer/CopyrightRow/index.static.ts
- packages/vital-layout/src/components/Footer/CopyrightRow/index.ts
Clean up the exports of CopyrightRow
With vital demo site:
- Run Static and confirm Copyright appears 
- Run Edit and confirm Copyright works as normal (appears & editable)
Tested as well on https://deploy-preview-24--neon-caramel-1c470e.netlify.app/
using this Canary PR : https://github.com/wodenx/bodiless-demo/pull/24
> bug(vital-layout): Update the exports for CopyrightRow

- packages/__vital__/src/shadow/@bodiless/vital-card/FlowContainer.ts
Fix shadowing of cards in __vital__ package so that ContentLibrary works as expected
* Verify content library works as expected now without it disappearing as its added to content library.  https://github.com/johnsonandjohnson/Bodiless-JS/issues/1960
* Verify only Basic & Hero type cards are available in vital demo site and they work as expected.
> fix(__vital__): Fix ContentLibrary not working on vital cards

- packages/gatsby-theme-bodiless/src/dist/Page.bl-edit.tsx
- sites/__minimal__/.env.site
- sites/__vital__/.env.site
Add a BODILESS_DISABLE_EDITOR env var which disables the editor even when running in development mode.
Will allow running a bodiless site using an alternative editor (eg Stackbit).
> feat(gatsby-theme-bodiless): Allow disabling of editor in dev mode.

- packages/bodiless-backend/src/page.ts
- packages/bodiless-filtering/src/TagButton/TagModel.tsx
- packages/bodiless-filtering/src/TagButton/types.tsx
- packages/bodiless-filtering/src/TagButton/withTagButton.tsx
- packages/bodiless-next/src/getStaticPaths.ts
- packages/bodiless-next/src/getStaticProps.ts
- packages/bodiless-page/src/Operations/PageVerification.ts
- packages/bodiless-page/src/RedirectAlias/form.tsx
- sites/vital-demo-next/next.config.js
> fix(filtering, page, next): editing bugs on NextJS

- .github/workflows/build-test-lint-simple.yml
- .github/workflows/test-workflow-listener.yml
Changes
* ready-to-test label will trigger testing workflow
* skip-tests label will mark testing workflow as skipped allowing the PR to be merged
* any other labels won't have any effect on testing workflow
> ci: Trigger test workflow only on test labels

- packages/vital-examples/src/intro/section-example/README.md
- packages/vital-examples/src/intro/section-example/components/Section/tokens/exampleSection.ts
- packages/vital-section/src/Components/Section/tokens/vitalSection.ts
- Updated patterns and documentation on how to use the Default Content with the Schema domain.
- Visual check if Section Title, Link and Description are visible on the example page.
> fix(vita-section, vital-examples): Update patterns for the Schema and DefaultContent

- packages/bodiless-documentation/src/defaultToc.ts
- Remove moved file "Shadowing.md" from default ToC, to fix endless doc build cycle.
> docs(bodiless-documentation): Fix endless cycle

- packages/bodiless-documentation/src/tree.ts
- packages/bodiless-ga4/bodiless.docs.json
- packages/bodiless-organisms/bodiless.docs.json
- packages/vital-editors/bodiless.docs.json
- packages/vital-elements/bodiless.docs.json
- packages/vital-examples/bodiless.docs.json
- packages/vital-layout/bodiless.docs.json
- Fix sections in the Bodiless documentation sidebar from generating pages in the reverse order from what is configured.
- Update `bodiless.docs.json` files for sections that were intentionally reversed to compensate for this bug.
1. Find an existing `bodiless.docs.json` file (e.g., [`packages/vital-examples/bodiless.docs.json`](https://github.com/misterjones/Bodiless-JS/blob/99290901589bb3f9dd7daf214400725f52da3182/packages/vital-examples/bodiless.docs.json)).
2. Locally, navigate to `sites/test-site` and run `npm run docs`.
3. Confirm that the section configured by the `bodiless.docs.json` file generates its pages in the same order as they are listed in the file.
> fix: Page order in Docsify

- packages/vital-examples/doc/Curriculum/Lessons/BackgroundImages.md
- packages/vital-examples/doc/Curriculum/Lessons/CustomizeDesignTokens.md
- packages/vital-examples/doc/Curriculum/Lessons/DevelopANewComponent.md
- packages/vital-examples/doc/Curriculum/Lessons/ReusableTokens.md
- packages/vital-examples/doc/Curriculum/Lessons/ShadowASimpleComponent.md
- packages/vital-examples/src/background-images/components/Footer/tokens/exampleFooter.ts
- packages/vital-examples/src/customizing-design-tokens/components/TextDecoration/tokens/exampleTextDecoration.ts
- packages/vital-examples/src/customizing-design-tokens/components/Typography/tokens/exampleTypography.ts
- packages/vital-examples/src/intro/section-example/components/ElementsList/tokens/exampleElementsList.ts
- packages/vital-examples/src/intro/section-example/components/Section/tokens/exampleSection.ts
- packages/vital-examples/src/reusable-tokens/components/Card/tokens/exampleCard.ts
- packages/vital-examples/src/reusable-tokens/components/Radius/tokens/exampleRadius.ts
- packages/vital-examples/src/shadowing-simple-component/components/Buttons/tokens/exampleButtons.ts
- packages/vital-section/src/Components/Section/SectionClean.tsx
- packages/vital-section/src/Components/Section/tokens/vitalSection.ts
- sites/vital-examples/src/pages/intro/section-example.tsx
- Perform "doc clean-up" on Curriculum Lessons.
- Fix typos, formatting, etc.
- Replace applicable code blocks with embedded code from the associated example files.
- Update example files.
- Restrict code comments to column 78 (for Docsify).
> docs(vital-examples): Clean up Curriculum Lessons

- packages/bodiless-i18n/package.json
- packages/bodiless-layouts/package.json
- packages/bodiless-schema-org/package.json
- packages/gatsby-theme-bodiless/package.json
- packages/vital-accordion/package.json
- packages/vital-button/package.json
- packages/vital-card/package.json
- packages/vital-content-listing/package.json
- packages/vital-demo/package.json
- packages/vital-flowcontainer/package.json
- packages/vital-image/package.json
- packages/vital-layout/package.json
- packages/vital-list/package.json
- packages/vital-meta/package.json
- packages/vital-search/package.json
- packages/vital-section/package.json
- packages/vital-table/package.json
- packages/vital-templates/package.json
- packages/vital-youtube/package.json
- Restore Bodiless/Vital API docs in the Bodiless documentation.
- This commit reverses commit 3e97fa59da599c5ad08873a5e89c77c2897d0590.
- See: <https://github.com/johnsonandjohnson/Bodiless-JS/pull/2110/commits/3e97fa59da599c5ad08873a5e89c77c2897d0590>
01. Run `test-site` docs.
```
cd sites/test-site
npm run docs
```
02. Go to http://localhost:3000/#/Development/API/.
03. See that a number of packages (12) are listed.
> docs: Restore API docs
