johnsonandjohnson/Bodiless-JS

- .travis.yml
- packages/bodiless-documentation/doc/README.md
- packages/bodiless-documentation/src/writeSymlinksFromTree.ts
Hosts docs to github pages and builds them with Travis.
- Verify that docs site is running at https://johnsonandjohnson.github.io/Bodiless-JS
- Verify that changes to docs are publshed (only possible after merge)
Closes #5
> feat: Host docs on GitHub Pages

- packages/bodiless-accessibility/package.json
- packages/bodiless-backend/package.json
- packages/bodiless-bv/package.json
- packages/bodiless-components/package.json
- packages/bodiless-core-ui/package.json
- packages/bodiless-core/package.json
- packages/bodiless-documentation/package.json
- packages/bodiless-layouts-ui/package.json
- packages/bodiless-layouts/package.json
- packages/bodiless-migration-tool/package.json
- packages/bodiless-organisms/package.json
- packages/bodiless-psh/package.json
- packages/bodiless-richtext-ui/package.json
- packages/bodiless-richtext/package.json
- packages/bodiless-ui/package.json
- packages/fclasses/package.json
- packages/gatsby-plugin-ssi/package.json
- packages/gatsby-theme-bodiless/package.json
> chore(*) upstream update

- package-lock.json
- packages/bodiless-backend/src/backend.js
- packages/gatsby-theme-bodiless/package.json
- packages/gatsby-theme-bodiless/src/dist/BackendClient.ts
- packages/gatsby-theme-bodiless/src/dist/GitProvider.tsx
- Add author to content commits if author exists. 
- TBD
#25
> GH-26 Add author to commits if possible.

- packages/bodiless-core/package.json
- packages/bodiless-documentation/doc/About/CorePrinciples.md
- packages/bodiless-documentation/doc/README.md
- packages/bodiless-migration-tool/conf/gatsby-node.js
- packages/bodiless-migration-tool/doc/Technical/MigrationTool.md
> Remove naming convention

- .platform.app.yaml
- examples/test-site/edit/platform.custom.sh
- examples/test-site/edit/platform.sh
- packages/bodiless-psh/README.md
- packages/bodiless-psh/resources/edit/platform.sh
- Updates platform.sh configurations so that GitHub PR branches can be properly deployed to edit environments.
- Currently only implemented for "fresh" deployment .   Incremental deploys are not yet supported.
- Create a PR
- Validate that both static and edit apps are properly deployed to platform.sh
> chore(test-site): Deploy GitHub PR's to p.sh

- .gitignore
- .travis.yml
- cypress.json
- cypress/fixtures/example.json
- cypress/integration/link_menu.spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- examples/starter/package-lock.json
- examples/test-site/package-lock.json
- jest.config.js
- package-lock.json
- package.json
- Adds cypress
- Adds start-server-and-test
- Adds travis config
- Adds ci-related test scripts to package.json
#References
#76
> chore: cypress and travis ci

- examples/test-site/edit/platform.custom.sh
- package.json
- packages/bodiless-psh/resources/edit/platform.custom.sh
- Remove lerna from p.sh
Fixes: https://github.com/johnsonandjohnson/Bodiless-JS/issues/103
> fix(psh): platform.sh files get created with lerna

- packages/bodiless-components/__tests__/Image.test.tsx
- packages/bodiless-components/__tests__/Link.test.tsx
- packages/bodiless-core/__tests__/hoc.test.tsx
- packages/bodiless-core/__tests__/withEditToggle.test.tsx
- packages/bodiless-richtext/__tests__/HoverMenu.test.tsx
- Add Image component tests
- Add Link component tests
- Add HOC unit test
- Add withEditToggle unit test
- Add HoverMenu unit test
> test: Image / Link integration and misc unit tests

- examples/starter/package-lock.json
- examples/test-site/package-lock.json
- package-lock.json
- package.json
- Package version updated
- Example site package-lock updated.
> Chore: Example site package dependency update after v0.0.40.

- packages/bodiless-psh/resources/static/static.platform.sh
- Make sure the SSI_CONF_PATH variable has a consistent name over different files and repos.
- E.g. look at .platform.app.yaml
> chore(platform.sh): Unify variable name for SSI configuration path

- packages/bodiless-migration-tool/src/evaluate-page.ts
* extended selector to extract a list of video resources
> fix(migration-tool): scrape video file injected using video html element

- packages/bodiless-psh/README.md
- Updates to @bodiless/psh README.
> docs(psh): Add instructions on how to obtain private registry auth token.

- .travis.yml
- packages/bodiless-documentation/doc/About/SiteBuildBasics.md
- Update tutorial to reflect using starter.
- Add back COPYFILES var in travis build to properly build github pages.
> docs(documentation): Minor updates to tutorial; Fix gh-pages build.

- lerna.json
- package.json
Use "release" branch to push publication.
- Checkout "release" branch with this update.
- run `npm run setup`
- publish patch with `npm run publish:patch`
Fixes: #16
> feat(release, publish): Automate package publication on GitHub - release branch update.

- packages/bodiless-migration-tool/doc/Technical/MigrationTool.md
document the actual behavior when creating common component.
fixes: #295
> docs(Migration tool): Document issue with hydrating common element with dynamic features.

- packages/bodiless-backend/src/backend.js
- Revert pulling the changes to local when "Pull" is executed
> Revert pull

- packages/bodiless-ui/src/elements.tsx
- Remove horizontal scroll bar.
> fix(ui): Remove horizontal scroll bar.

- examples/test-site/src/data/pages/flow-container/index.tsx
- packages/bodiless-layouts-ui/src/FlowContainer.tsx
- packages/bodiless-layouts-ui/src/SortableResizableWrapper.tsx
- packages/bodiless-layouts/src/FlowContainer/SortableChild.tsx
- packages/bodiless-layouts/src/FlowContainer/StaticFlowContainer.tsx
- packages/bodiless-layouts/src/FlowContainer/model.ts
- packages/bodiless-layouts/src/FlowContainer/types.ts
- packages/bodiless-layouts/src/SlateSortableResizable.tsx
- packages/bodiless-layouts/src/index.ts
- Fix issues with flow container data (refresh and unnecessary save)
- Fix snap issues
- Add snap indicator so you'll know where you'll snap to when done resizing.
- Includes significant refactor of SortableChild
- See Linked Bugs
Fixes #657 
Fixes #654 
Fixes #656
> fix(layouts): Various FlowContainer bugs + Snap Indicator

- .github/workflows/build-test-lint-simple.yml
initial commit to add gh actions worfflow
> ci: Init github actions ci.

- .github/workflows/publish.yml
> feat(CI/CD): Package publish workflow

- packages/bodiless-search/src/components/ResponsiveSearchBox.tsx
- packages/bodiless-search/src/components/Search.tsx
* close search box on submit on mobile
> fix(search): close mobile search box on submit

- packages/bodiless-search/src/components/Search.tsx
* close mobile search box on enter
> fix(search): close mobile search box on enter

- examples/starter/src/components/Editors/withEditor.tsx
- examples/test-site/src/components/Editors/withEditor.tsx
- examples/test-site/src/data/pages/richtext/index.tsx
- packages/bodiless-core/src/withChild.tsx
* added description for "Alphabetic Full Rich Text"
* changed Editor design key in test-site and starter
* added doc for withChild
> chore: Make text editors designable - small improvements

- .github/workflows/docs.yml
> feat(github action): Add Github action for doc publishing

- packages/bodiless-core/src/withCompoundForm.tsx
* fixed the problem described in #950
* see str in #950
Fixes #950
> fix(core): Cannot read property 'href' of undefined'

- examples/test-site/src/components/SocialShare/index.tsx
- Fixes a bug in the configuration of social share on the test site.
Fixes #956
> fix(test-site): Broken image upload for share (#955)

- examples/test-site/src/components/Carousel/carousel.css
- examples/test-site/src/components/Carousel/token.tsx
- examples/test-site/src/data/pages/carousel/index.tsx
- examples/test-site/tailwind.config.js
- packages/bodiless-carousel/src/components/CarouselClean.tsx
- packages/bodiless-carousel/src/components/asEditableCarousel.ts
- packages/bodiless-carousel/src/components/token.tsx
* fix: console warning on /carousel test-site page load and carousel navigation
* fix: disabled navigation button styles
* fix: horizontal card styles in chameleon carousel
* chore: added a carousel example with infinitive loop
> fix(carousel): carousel remediation

- packages/bodiless-core/__tests__/withParent.test.tsx
- packages/bodiless-core/src/index.ts
- packages/bodiless-core/src/withParent.tsx
- New `withParent` utility function.
- Currently no use-cases on the test-site.
- Review and confirm Unit tests pass.
> feat(core): Implement withParent

- examples/test-site/src/data/pages/files/index.tsx
- packages/bodiless-components-ui/src/FileUpload.tsx
- packages/bodiless-components-ui/src/index.ts
* fix: selected file styles in the file upload form, a case when file with long name is uploaded
*  test a case when files with long names are uploaded
> fix(components): selected file styles in the file upload form

- examples/test-site/src/components/Menu/Menu.token.tsx
- packages/bodiless-components/src/Link/index.ts
- packages/bodiless-components/src/List/asBodilessList.tsx
- packages/bodiless-core/src/index.ts
- packages/bodiless-navigation/src/Menu/Menu.token.tsx
- packages/bodiless-navigation/src/Menu/MenuTitles.tsx
- packages/bodiless-navigation/src/Menu/asAccessibleMenu.tsx
- packages/bodiless-navigation/src/Menu/asBodilessMenu.tsx
- packages/bodiless-navigation/src/Menu/index.ts
- packages/bodiless-navigation/src/Menu/withMenuContext.tsx
- packages/bodiless-navigation/src/Menu/withMenuItemContext.tsx
- packages/bodiless-navigation/src/Menu/withSubMenu.tsx
- packages/bodiless-navigation/tailwind.config.js
> feat(navigation): Menu Accessibility

- packages/bodiless-bv/src/components/BVLoader.tsx
- packages/bodiless-bv/src/getBVScriptUrl.ts
Allow passing BV config as a prop to any BV component.
> feat(bv): Enable sites to configure BV per page.

- examples/test-site/edit/force-build
- examples/test-site/src/components/Card/token.tsx
- examples/test-site/src/data/pages/menu/index.tsx
- examples/test-site/tailwind.config.js
- packages/bodiless-navigation/package.json
- RTL toggle is added to the menu page
- RLT Menu now can be tested on the `/menu` page when RTL toggle is toggled on
- No changes to the menu component. Only the toggle on the test page is added
> feat(navigation): Menu Supports RTL

- packages/bodiless-psh/src/psh-url-replacer.ts
> chore(psh): adding debug message for variable generation during psh deployment

- packages/bodiless-core/src/components/LocalContextMenu.tsx
> Fix context menu does not display for full-bleed items

- packages/bodiless-components/doc/Chameleon.md
Fixes some typos in bodiless chameleon docs.
> doc(components): Fix typos.

- packages/bodiless-filtering/src/FilterByGroup/FilterByGroupContext.tsx
- packages/bodiless-filtering/src/FilterByGroup/index.tsx
- Added missing bodiless export
> fix(filtering): Fix missing export

- packages/bodiless-components/package.json
- packages/bodiless-ui/package.json
> fix(adminui): Fix admin ui issue

- packages/bodiless-layouts/src/ContentLibrary/ContentLibraryIndicator.tsx
- packages/bodiless-layouts/src/ContentLibrary/withLibraryComponents.tsx
> fix(unlink): Fix warning when unlinking library

- packages/bodiless-psh/README.md
Add instructions on how to deal with memory limitations when using BodilessJS on platform.sh development environments.
> docs(psh): Document known memory limitations on p.sh

- examples/test-site/src/components/YouTube/index.tsx
- packages/gatsby-theme-bodiless/src/dist/withMovePageButton.tsx
Fix lodash import on withMovePageButton.tsx
> Fix lodash import on withMovePageButton.tsx

- packages/gatsby-theme-bodiless/__tests__/create-pages.test.ts
- packages/gatsby-theme-bodiless/__tests__/gatsby-node.test.ts
> unittest fix on git info

- .github/workflows/ensure-semantic-pr.yml
Action that performs check of conventional commits added.
Closes #1475
> ci: prevent PR merge if commit message is not semantic

- packages/bodiless-webpack/package.json
- packages/bodiless-webpack/src/index.ts
- packages/bodiless-webpack/src/statoscopePlugin.ts
- sites/__cxstarter__/gatsby-config.js
- sites/__cxstarter__/gatsby-node.js
- sites/__cxstarter__/package.json
- sites/test-site/gatsby-config.js
- sites/test-site/gatsby-node.js
- sites/test-site/package.json
Add [statoscope](https://github.com/statoscope/statoscope) webpack plugin to bodiless/webpack.
Provides to the devs a comfortable tool to analyse the webpack composition
> feat(bodiless-webpack): Add statoscope webpack plugin

- packages/bodiless-layouts-ui/src/ComponentSelector.tsx
Prefixe component picker classes with bl-
> fix(bodiless-layouts-ui): cmponent picker in site

- packages/fclasses/src/tailwindcss/mergeConfigs.ts
- sites/__vital__/tailwind.config.js
- sites/test-site/tailwind.config.js
…dle rebuild on edit env
fixes: #1584
> fix(Tailwindcss, fclasses): Demo site content changes causing HMR bundle rebuild on edit env

- sites/test-site/src/components/Search/token.tsx
> fix(test-site): restore focus on search input.

- packages/bodiless-psh/resources/edit/platform.sh
- sites/test-site/edit/platform.sh
Credentials in git clone request removed.
Credentials helper applied.
Fixes #1503
> ci: hide git user password

- packages/bodiless-components/src/PageDisable/form.tsx
- packages/bodiless-core-ui/src/LocalContextMenu.tsx
- packages/bodiless-core-ui/src/PageOverlay.tsx
- packages/bodiless-core/src/Git/RemoteChanges.tsx
- packages/bodiless-layouts-ui/src/ComponentSelector.tsx
- packages/bodiless-layouts/src/ContentLibrary/ContentLibraryIndicator.tsx
- packages/bodiless-page/src/RedirectAlias/form.tsx
- packages/bodiless-richtext-ui/src/components/PreviewWrapper.tsx
- packages/bodiless-tokens/src/TokenEditor/withTokenEditorComponent.tsx
- packages/bodiless-ui/README.md
- packages/bodiless-ui/bodiless.tailwind.config.js
- packages/bodiless-ui/src/Spinner.tsx
- packages/bodiless-ui/src/elements.tsx
- packages/vital-editors/src/components/EditorPlain/util.tsx
Fix missing bl-black for RTE preview in component selector
Search for className & AddClasses and audit all missing bl- classes.
> fix(bodiless-ui): try find all missing bl- prefixes in editor 

- packages/fclasses/__tests__/tailwindcss.test.ts
> fix(Tailwind): unit test tailwind

- UPGRADE.md
- packages/bodiless-richtext/src/components/PluginButton.tsx
- packages/bodiless-tokens/README.md
- packages/bodiless-ui/bodiless.tailwind.config.js
- packages/bodiless-ui/src/elements.tsx
- packages/fclasses/README.md
- changes icons
- make close smaller
- add hover state for submit
> fix(bodiless-ui): fix close/submit icon, Warning, RTE icons

- packages/bodiless-page/src/Forms/MenuFormPageNew.tsx
> fix(bodiless-page): internal server error new page

- packages/vital-elements/src/components/Color/tokens/vitalColor.ts
- packages/vital-elements/tailwind.config.js
- packages/vital-layout/src/components/Footer/tokens/vitalFooter.ts
- packages/vital-navigation/src/components/Separator/tokens/vitalSeparator.ts
* border-white-400 doesn't exist anymore so added custom color that matches design.
> fix(vital-site): fix separator color

- packages/bodiless-richtext/src/components/PluginButton.tsx
* Remove override to force to 24px
> fix(bodiless-richtext): Restore to 30px(default)

- packages/vital-list/package.json
- packages/vital-meta/package.json
> fix(bodiless-meta, bodiless-listing): add publishConfig for publishing

- packages/bodiless-ui/src/elements.tsx
> fix(Tailwind): close color

- .github/workflows/pr-canary-release.yml
- .github/workflows/release.yml
- lerna.json
Action to publish canary released packages app on PRs added.
Action to perform manual release added.
Closes #1276
> ci: automated package publishing implemented

- .github/workflows/pr-canary-release.yml
Trigger setup updated to run only on PRs to main
Create a pr to main - action is triggered
Create a pr to any different branch - action is not triggered
Fixes #1649
> fix: trigger setup updated

- edit/platform.sh
- packages/bodiless-psh/resources/edit/platform.sh
> fix(bodiless-psh): git credential helper issues.

- lerna.json
Main branch added to the allowBranch parameter
Closes #1644
> ci: allowBranch param extended with main

- packages/bodiless-backend/src/backend.js
- packages/bodiless-core/src/Git/SaveChanges.tsx
- packages/bodiless-page/src/RedirectAlias/form.tsx
> fix(bodiless-page): 500 error message update

- packages/bodiless-backend/src/git.js
> fix(bodiless-backend): copy root repo credential helper to tmp clone

- .github/workflows/prerelease.yaml
> ci: added prerelease action

- .github/workflows/docs.yml
- edit/platform.custom.sh
- package.json
- packages/bodiless-cli/src/helpers/AbstractNew.ts
- packages/bodiless-search/doc/Search.md
- sites/minimal-demo/package.json
> fix(docs): fixing failed gh-page publishing

- .github/workflows/prerelease.yaml
> ci: manual trigger added

- scripts/psh-setup-starter.js
> fix: psh-setup-starter script fixed

- scripts/psh-setup-starter.js
> fix: duplicate call removed

- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
> ci: update value of minimal approvals

- packages/bodiless-documentation/doc/README.md
> docs: Remove instant start oc

- packages/bodiless-documentation/doc/README.md
- Replace internal doc link with Bodiless documentation links in project root README.
> fix(documentation): fixing root README.md links

- packages/bodiless-documentation/doc/About/GettingStarted.md
Clarify the process of installing pre-1.x site.
> docs: Fix startup doc for prerelease versions

- .eslintignore
- package.json
- playwright/pages/accordion-page.ts
- playwright/pages/base-page.ts
- playwright/pages/cards-page.ts
- playwright/pages/editor-menu-page.ts
- playwright/pages/file-submenu-page.ts
- playwright/pages/flow-container-page.ts
- playwright/pages/link-toggle-page.ts
- playwright/pages/pdp-page.ts
- playwright/pages/vital-cards.ts
- playwright/pages/vital-generic-template.ts
- playwright/pages/vital-layout.ts
- playwright/pages/vital-page.ts
- playwright/pages/vital-product.ts
- playwright/pages/vital-typography.ts
- playwright/tests/smoke-deprecated/cards.spec.ts
- playwright/tests/smoke-deprecated/componentPicker.spec.ts
- playwright/tests/smoke-deprecated/editorMenu.spec.ts
- playwright/tests/smoke-deprecated/fileSubmenu.spec.ts
- playwright/tests/smoke-deprecated/flowContainer.spec.ts
- playwright/tests/smoke-deprecated/linkToggle.spec.ts
- playwright/tests/smoke-deprecated/pdp.spec.ts
- playwright/tests/smoke-deprecated/singleAccordion.spec.ts
- playwright/tests/smoke/components-visual.spec.ts
- playwright/tests/smoke/vital-cards.spec.ts
- playwright/tests/smoke/vital-typography.spec.ts
* Enable ESlint for playwright tests
* Added tests for typography, layout, product and generic template
> test: Add tests for typography, layout, product and generic template

- .github/workflows/build-test-lint-simple.yml
- playwright/pages/index.ts
- playwright/pages/vital-accordion.ts
- playwright/pages/vital-buttons.ts
- playwright/pages/vital-cards.ts
- playwright/pages/vital-page.ts
- playwright/pages/vital-video.ts
- playwright/tests/data/faq-schema.json
- playwright/tests/smoke/components-visual.spec.ts
- playwright/tests/smoke/vital-accordion.spec.ts
- playwright/tests/smoke/vital-buttons.spec.ts
- playwright/tests/smoke/vital-cards.spec.ts
- playwright/tests/smoke/vital-typography.spec.ts
- playwright/tests/smoke/vital-video.spec.ts
Added tests for:
* videos
* buttons
* accordions
> test: Add tests for vital buttons, accordions and videos

- playwright/tests/smoke/components-visual.spec.ts
> test: Improve visual test naming

- .github/workflows/build-test-lint-simple.yml
- playwright/tests/smoke/components-visual.spec.ts
> test: Use pull request title as Applitools batch name

- packages/vital-layout/src/components/Header/HeaderClean.tsx
- packages/vital-layout/src/components/Header/types.ts
Add optional Utility menu slots above header
> fix(vital-layout): Add outer Utility menu

- packages/vital-layout/src/components/Footer/CopyrightRow/CopyrightRowClean.tsx
- packages/vital-layout/src/components/Footer/CopyrightRow/types.ts
Move Disclaimer and add Wrapper
> fix(vital-layout): Move Disclaimer

- .github/workflows/build-test-lint-simple.yml
> chore: Add upgrade branches to test workflow

- .github/workflows/build-test-lint-simple.yml
> chore: Try again to build branches targeting upgrade/*

- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .platform.app.yaml
- edit/.platform.app.yaml
- packages/bodiless-documentation/doc/About/GettingStarted.md
- packages/bodiless-psh/resources/edit/edit.platform.app.yaml
- packages/bodiless-psh/resources/static/static.platform.app.yaml
> fix(node-version): update node version to 18.16

- packages/bodiless-documentation/src/defaultToc.ts
> fix(docs): fixing page build cycle

- .github/actions/build/action.yml
- .github/actions/playwright/action.yml
- .github/workflows/build-test-lint-simple.yml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
- package.json
- playwright.config.ts
* run functional and visual component tests in parallel (CI run takes ~21 min)
* cleaned up  a bit package.json and test config file
> test: Optimize tests execution in CI

- .github/workflows/build-test-lint-simple.yml
- package.json
> fix(github action): rename test script

- sites/vital-demo-next/src/pages/_document.tsx
Update ID & datalayer name
- Verify on vital-demo-next that ID is update to GTM-WSPHT2V (three instances of it two in head & one at beginning of body) and datalayer name is now dataLayer
- Static link: https://bodiless-js-next-ghme4dyvg-jnj-demo-account.vercel.app/
> fix(vital-demo-next): update id & data layer name

- playwright.config.ts
- playwright/tests/config/vital-test-parameters.ts
- playwright/tests/smoke/components-accessibility.spec.ts
- sites/vital-demo-next/src/data/pages/styleguide/section/index.json
- sites/vital-demo-next/src/data/pages/styleguide/section/template.json
- sites/vital-demo-next/src/data/site/content-listing$content$a0c1dac0-06cf-11ee-9bdb-5b922047813b$eyebrow.json
- sites/vital-demo-next/src/data/site/content-listing$content$a0c1dac0-06cf-11ee-9bdb-5b922047813b$image.json
- sites/vital-demo-next/src/data/site/content-listing$content$a0c1dac0-06cf-11ee-9bdb-5b922047813b$title.json
- sites/vital-demo-next/src/data/site/content-listing$content$a0c1dac0-06cf-11ee-9bdb-5b922047813b.json
- sites/vital-demo-next/src/data/site/content-listing$content.json
> test: Migrate tests to vital-demo-next site

- package.json
- turbo.json
> fix(build): build watch for selected packages

- playwright.config.ts
- playwright/tests/config/vital-test-parameters.ts
- playwright/tests/smoke/components-accessibility.spec.ts
> test: Enable Video tests

- playwright/tests/config/vital-test-parameters.ts
- playwright/tests/smoke/components-accessibility.spec.ts
> test: Enable accessibility check for 'list' rule

- playwright/pages/vital-buttons.ts
- playwright/tests/smoke/vital-buttons.spec.ts
> test: Remove no longer used buttons

- .github/workflows/build-test-lint-simple.yml
- lighthouserc.js
> test: Add Lighthouse performance checks

- .github/workflows/build-test-lint-simple.yml
- .github/workflows/test-workflow-listener.yml
- lighthouserc.js
> test: Build nextjs site before lighthouse run
